### ISSUE TITLE
文字コードがUTF-8のファイルを読み込ませたときにエラーが出る

### ISSUE THREAD

**Issue by testuser1111111-nd** [Chatyusha/sucellus#1]
バージョン
Python 3.9.13
Windows 11 Pro 21H2 22000.1696
エラー出力
``` PS C:\Users\username\bushi2023\bushi2023> python3 build.py       
>>> 自分のハンドルネームを入力してください(例: chito)sug
Traceback (most recent call last):
  File "C:\Users\username\bushi2023\bushi2023\build.py", line 8, in <module>
    parser.read_file(f"./sample/{filename}.md")
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\syntarch\parser.py", line 30, in read_file
    self.read_text = Path(file_path).read_text()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1267, in read_text
    return f.read()
UnicodeDecodeError: 'cp932' codec can't decode byte 0x8f in position 37: illegal multibyte sequence
```

parser.pyの30行目を以下の通りに変更することで応急処置はできることが確認されたが、この方法はUTF-8以外の文字コード形式を受け付けなくなるので気を付けるべき　ちなみに応急処置用のプルリクはこれで送ってる
``` self.read_text = Path(file_path).read_text(encoding="utf-8") ```

**Comment by testuser1111111-nd** [comment]
出力ファイルがShift-JISなんだけどこれもしかして意図的? ならissueもプルリクも無視して閉じといて

**Comment by testuser1111111-nd** [comment]
どうやらおま環のようでした　見たら閉じといてくれ
